<?php

  function additup_menu() {
    $items = array();
    $items['add_it_up'] = array(
      'title' => t('Add It Up'),
      'type' => MENU_NORMAL_ITEM,
      'access callback' => TRUE,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('adder_form'),
    );
    $items['result'] = array(
      'title' => 'Result',
      'type' => MENU_CALLBACK,
      'access callback' => TRUE,
      'page callback' => 'adder_result'
    );
    return $items;
  }

  function adder_form() {
    $form = array();

    $form['number_one'] = array(
      '#title' => 'First Number',
      '#type' => 'textfield',
      '#description' => t('Enter a number.'),
    );

    $form['number_two'] = array(
      '#title' => 'Second Number',
      '#type' => 'textfield',
      '#description' => t('Enter a number to add to the first.'),
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Add your numbers',
    );

    return $form;
  }

  function adder_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['number_one'];
    $second_number = $form_state['values']['number_two'];
    $added_result = $first_number + $second_number;
    $_SESSION['added_numbers'] = $added_result;
    $form_state['redirect'] = 'result';  
  }

  function adder_result() {
    $result = $_SESSION['added_numbers'];
    return "Your numbers have been added: $result.";
  }